# Generated by Django 4.2.7 on 2023-11-16 05:53

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('mobile_otp', models.CharField(max_length=10)),
                ('mobile_otp_expired', models.IntegerField(default=0)),
                ('email_otp', models.CharField(max_length=10)),
                ('email_otp_expired', models.IntegerField(default=0)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None, unique=True)),
                ('mobile_verified', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('bio', models.CharField(blank=True, default=False, max_length=200, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='Profile-images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
