# Generated by Django 4.2.7 on 2023-11-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_otp',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_otp',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
