# Generated by Django 4.2.7 on 2023-11-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_email_otp_alter_profile_mobile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
