# Generated by Django 4.2.7 on 2023-11-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_otp',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_otp',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
